//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEcommerceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public string Id { get; set; }
        public string IdReceiver { get; set; }
        public string IdSender { get; set; }
        public System.DateTime Date { get; set; }
        public string Content { get; set; }
        public Nullable<bool> HaveSeen { get; set; }
    
        public virtual MUser MUser { get; set; }
        public virtual MUser MUser1 { get; set; }
    }
}
