//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEcommerceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public string IdOrder { get; set; }
        public string IdProduct { get; set; }
        public string IdRating { get; set; }
        public string ImageProduct { get; set; }
        public string Size { get; set; }
        public int Count { get; set; }
        public double TotalPrice { get; set; }
    
        public virtual MOrder MOrder { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Product Product { get; set; }
    }
}
