//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEcommerceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingInfo
    {
        public long Id { get; set; }
        public long IdRating { get; set; }
        public int IdProduct { get; set; }
        public Nullable<int> Rating { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Rating Rating1 { get; set; }
    }
}
