//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEcommerceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingInfo
    {
        public string IdUser { get; set; }
        public string IdRating { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateReply { get; set; }
    
        public virtual MUser MUser { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
