//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFEcommerceApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public string IdUser { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public Nullable<int> Provider { get; set; }
        public string Salt { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual MUser MUser { get; set; }
    }
}
