//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public string IdOrder { get; set; }
        public string IdProduct { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<long> TotalPrice { get; set; }
    
        public virtual MOrder MOrder { get; set; }
    }
}
